### ISSUE TITLE
License inquiry

### ISSUE THREAD

**Issue by manfred-z** [lau-zudelova/bunbun-kanban-board#2]
Thank you for creating a great Kanban board!

I am reaching out to inquire about the licensing of Bunbun board. I noticed that currently, the project does not specify an open-source license. As someone interested in using and contributing, the absence of a license makes it difficult to understand how the software can be legally used or modified.

I was wondering if you have considered adding an open-source license to your project? Specifically, a license such as the GNU General Public License ([GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/)) could be beneficial. The GPL is widely used in the open-source community and ensures that derivative works will also remain open source, thus contributing to the open-source ecosystem.

Of course, the choice of a license is entirely up to you, and I respect your decision on how you wish to manage your project. I just wanted to raise this point as the addition of a clear license could potentially increase the project's usability and clarity regarding legal permissions.

Thank you for your time and consideration. I look forward to any possibility of further discussion or questions you might have.

**Comment by lau-zudelova** [comment]
Hey, thank you for noting this! 

Currently I don’t have access to my PC, so I will update the license later. I will use the GPL license, you can do whatever you want in accordance to this license in the meantime.

**Comment by lau-zudelova** [comment]
Actually it turned out to be easy on mobile as well!

**Comment by manfred-z** [comment]
Thank you for the quick reply and for agreeing to add the GPL! I appreciate your willingness to make the project more accessible for everyone.
